// Generated by CoffeeScript 1.3.3
(function() {
  var getFacebook, getTwitter, parseFacebook, parseTwitter;

  getTwitter = function(page) {
    var query;
    if (page == null) {
      page = 1;
    }
    query = "http://search.twitter.com/search.json?q=%40Nordstrom&callback=?&page=" + page;
    return $.ajax({
      url: query,
      type: 'GET',
      success: parseTwitter,
      complete: console.log('getTwitter complete'),
      dataType: 'jsonp',
      error: function(a, b, c) {
        return console.warn(a, b, c);
      }
    });
  };

  parseTwitter = function(json) {
    var k, p, peeps, results, x, z, _i, _j, _len, _len1, _ref, _results;
    results = json.results;
    console.log('ANALYZING TWITTERS');
    console.log(results.length + ' twitterers located');
    peeps = [];
    _ref = json.results;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      z = {
        name: x.form_user_name,
        icon: x.profile_image_url,
        message: x.text,
        link: null
      };
      peeps.push(z);
    }
    console.log(peeps);
    _results = [];
    for (_j = 0, _len1 = peeps.length; _j < _len1; _j++) {
      p = peeps[_j];
      k = sf.filter(p.message);
      if ($.isEmptyObject(k) === false && p !== void 0 && p.message !== void 0) {
        console.log(k);
        p.filter = k;
        console.log("Pushing to socialQueue");
        window.statusQueue.push(p);
        _results.push(sf.queues.addSocial(p));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  getFacebook = function(params) {
    var query;
    query = 'https://graph.facebook.com/search/?callback=&limit=1&q=Nordstrom&fields=message,from';
    return $.ajax({
      url: query,
      type: 'GET',
      success: parseFacebook,
      complete: console.log('getFacebook complete'),
      dataType: 'jsonp'
    });
  };

  parseFacebook = function(json) {
    var k, p, peeps, x, _i, _j, _len, _len1, _ref, _results;
    console.log('ANALYZING FACEBOOKS');
    console.log(json.data.length + ' facebooks located');
    peeps = [];
    _ref = json.data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      x = {
        name: x.from.name,
        icon: null,
        message: x.message,
        link: null
      };
      peeps.push(x);
    }
    console.log(peeps);
    _results = [];
    for (_j = 0, _len1 = peeps.length; _j < _len1; _j++) {
      p = peeps[_j];
      k = sf.filter(p.message);
      if ($.isEmptyObject(k) === false && p !== void 0 && p.message !== void 0) {
        console.log(k);
        p.filter = k;
        console.log("Pushing to socialQueue");
        window.statusQueue.push(p);
        _results.push(sf.queues.addSocial(p));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  window.getTwitter = getTwitter;

  window.getFacebook = getFacebook;

  $(document).ready(function() {
    var n, page, _results;
    window.statusQueue = [];
    getTwitter();
    getFacebook();
    page = 1;
    n = 0;
    _results = [];
    while (n < 10) {
      setTimeout('window.getTwitter', 10000, page++);
      _results.push(n++);
    }
    return _results;
  });

}).call(this);
