// Generated by CoffeeScript 1.3.3
(function() {
  var addToQueue, getFacebook, getTwitter, parseFacebook, parseTwitter;

  getTwitter = function(params) {
    var query;
    query = "http://search.twitter.com/search.json?q=%40Nordstrom&callback=?";
    return $.ajax({
      url: query,
      type: 'GET',
      success: parseTwitter,
      complete: console.log('getTwitter complete'),
      dataType: 'jsonp',
      error: function(a, b, c) {
        return console.warn(a, b, c);
      }
    });
  };

  parseTwitter = function(json) {
    var k, p, peeps, results, x, _i, _j, _len, _len1, _ref, _results;
    results = json.results;
    console.log('ANALYZING TWITTERS');
    console.log(results);
    peeps = [];
    _ref = json.results;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      x = {
        name: x.form_user_name,
        image: x.profile_image_url,
        message: x.text
      };
      peeps.push(x);
    }
    _results = [];
    for (_j = 0, _len1 = peeps.length; _j < _len1; _j++) {
      p = peeps[_j];
      k = addToQueue(p[2]);
      if (k) {
        p.filter = k;
        console.log("Pushing to socialQueue");
        window.statusQueue.push(p);
        _results.push(sf.socialQueue.push(p));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  getFacebook = function(params) {
    var query;
    query = 'https://graph.facebook.com/search/?callback=&limit=25&q=Nordstrom';
    return $.ajax({
      url: query,
      type: 'GET',
      success: parseFacebook,
      complete: console.log('getFacebook complete'),
      dataType: 'jsonp'
    });
  };

  parseFacebook = function(json) {
    var k, p, peeps, x, _i, _j, _len, _len1, _ref, _results;
    console.log('ANALYZING FACEBOOKS');
    console.log(json.data.length);
    peeps = [];
    _ref = json.data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      x = {
        name: x.from.name,
        image: null,
        message: x.message
      };
      peeps.push(x);
    }
    _results = [];
    for (_j = 0, _len1 = peeps.length; _j < _len1; _j++) {
      p = peeps[_j];
      k = addToQueue(p[2]);
      if (k) {
        p.filter = k;
        console.log("Pushing to socialQueue");
        window.statusQueue.push(p);
        _results.push(sf.socialQueue.push(p));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  addToQueue = function(message) {
    var keywords;
    keywords = sf.filter(message);
    if (keywords === {}) {
      return false;
    } else {
      return keywords;
    }
  };

  $(document).ready(function() {
    window.statusQueue = [];
    getTwitter();
    return getFacebook();
  });

}).call(this);
